//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public int AppConfigId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ValueString { get; set; }
        public Nullable<bool> ValueBit { get; set; }
        public Nullable<double> ValueFloat { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
