//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPaidHoliday
    {
        public int CompanyId { get; set; }
        public int PaidHolidayTypeId { get; set; }
        public int NumberOfDaysPerYear { get; set; }
    }
}
