//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayType
    {
        public HolidayType()
        {
            this.Holidays = new HashSet<Holiday>();
            this.HolidayTypeHolidays = new HashSet<HolidayTypeHoliday>();
        }
    
        public int HolidayTypeId { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateEntered_utc { get; set; }
    
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<HolidayTypeHoliday> HolidayTypeHolidays { get; set; }
    }
}
