//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PunchClockEntities : DbContext
    {
        public PunchClockEntities()
            : base("name=PunchClockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<HolidayType> HolidayTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<HolidayTypeHoliday> HolidayTypeHolidays { get; set; }
        public virtual DbSet<PaidHoliday> PaidHolidays { get; set; }
        public virtual DbSet<Punch> Punches { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CompanyEmployeeHolidayPaid> CompanyEmployeeHolidayPaids { get; set; }
        public virtual DbSet<CompanyHoliday> CompanyHolidays { get; set; }
        public virtual DbSet<CompanyPaidHoliday> CompanyPaidHolidays { get; set; }
    
        public virtual int usp_GetCompanyHolidays(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetCompanyHolidays", companyIdParameter);
        }
    
        public virtual ObjectResult<usp_GetCompanyHolidaysForEmployee_Result> usp_GetCompanyHolidaysForEmployee(Nullable<int> companyId, Nullable<int> employeeId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCompanyHolidaysForEmployee_Result>("usp_GetCompanyHolidaysForEmployee", companyIdParameter, employeeIdParameter);
        }
    }
}
