//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punch
    {
        public int PunchId { get; set; }
        public System.DateTime PunchDate { get; set; }
        public System.TimeSpan PunchIn { get; set; }
        public Nullable<System.TimeSpan> PunchOut { get; set; }
        public int UserId { get; set; }
        public bool IsManagerAccepted { get; set; }
        public bool RequestForApproval { get; set; }
        public string Comments { get; set; }
    
        public virtual User User { get; set; }
    }
}
