//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CompanyId { get; set; }
        public System.Guid GlobalId { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string LogoUrl { get; set; }
        public byte[] LogoBinary { get; set; }
        public int DeltaPunchTime { get; set; }
        public string RegisterCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
