//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Holidays = new HashSet<Holiday>();
        }
    
        public int CountryId { get; set; }
        public System.Guid CountryGuid { get; set; }
        public string Name { get; set; }
        public string TwoLetterIsoCode { get; set; }
        public string ThreeLetterIsoCode { get; set; }
        public string NumericIsoCode { get; set; }
        public byte Published { get; set; }
        public int DisplayOrder { get; set; }
        public string ExtensionData { get; set; }
        public System.DateTime CreatedOn_utc { get; set; }
    
        public virtual ICollection<Holiday> Holidays { get; set; }
    }
}
