//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public Holiday()
        {
            this.HolidayTypeHolidays = new HashSet<HolidayTypeHoliday>();
        }
    
        public int HolidayId { get; set; }
        public string HolidayName { get; set; }
        public string Description { get; set; }
        public int HolidayMonth { get; set; }
        public int HolidayDate { get; set; }
        public int HolidayTypeId { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual HolidayType HolidayType { get; set; }
        public virtual ICollection<HolidayTypeHoliday> HolidayTypeHolidays { get; set; }
    }
}
