//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int StateId { get; set; }
        public System.Guid StateGUID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Abbreviation { get; set; }
        public byte Published { get; set; }
        public int DisplayOrder { get; set; }
        public string ExtensionData { get; set; }
        public System.DateTime CreatedOn_utc { get; set; }
    }
}
