//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Companies = new HashSet<Company>();
            this.Punches = new HashSet<Punch>();
        }
    
        public int UserId { get; set; }
        public System.Guid GlobalId { get; set; }
        public int UserTypeId { get; set; }
        public int EmploymentType { get; set; }
        public int CompanyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string MiddleName { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> PasswordLastChanged { get; set; }
        public bool PasswordDisabled { get; set; }
        public string RegisteredTimeZone { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public System.DateTimeOffset DateCreated_utc { get; set; }
        public System.DateTimeOffset LastUpdated_utc { get; set; }
        public System.DateTimeOffset LastActivityDate_utc { get; set; }
        public string UserRegistered_IP { get; set; }
        public string Registered_MAC_Address { get; set; }
        public string LastActive_MAC_Address { get; set; }
        public string LastActivity_IP { get; set; }
    
        public virtual EmploymentType EmploymentType1 { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Punch> Punches { get; set; }

        public System.Data.Entity.EntityState State { get; set; }
    }
}
